int _putchar(char c );
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
 int factorial(int n);
int prime_finder(int x, int y);
int is_prime_number(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int calculate_sqrt(int n, int i);
int _putchar(char c);
int _isupper(int c);
int _isdigit(int c);
int mul(int a, int b);
void print_numbers(void);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int n);
void print_diagonal(int n);
void print_square(int size);
void print_triangle(int size);
void print_number(int n);
